#
#-------------------------------------------------------------------------------
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PyQt5.QtWidgets import *
import sys

from ui_main import Ui_MainWindow
# from ui_error import Ui_Error
# from ui_dialog import Ui_Dialog
from ui_function import *
#-------------------------------------------------------------------------------


# class dialogUi(QDialog):
#     '''Dialog window'''
#     def __init__(self, parent=None):
#         super(dialogUi, self).__init__(parent)
#         self.d = Ui_Dialog()
#         self.d.setupUi(self)


# class errorUi(QDialog):
#     '''Error window'''
#     def __init__(self, parent=None):

#         super(errorUi, self).__init__(parent)
#         self.e = Ui_Error()
#         self.e.setupUi(self)


class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        # Class Ui_MainWindow is autogenerated by PyQt5, method setupUi too
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Hides normal TopBar
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        # Adds minimizing, maximizing and closing functionality
        self.ui.exitBtn.clicked.connect(lambda: self.close())
        self.ui.minimizeBtn.clicked.connect(lambda: self.showMinimized())
        self.maximizeToggle = False
        self.ui.maximizeBtn.clicked.connect(lambda: self.maximize())


        # DRAGGING FUNCTIONS--------------------------------------------------------
        def moveWindow(event):
            print(event.button())
            print(Qt.LeftButton)
            if event.buttons() == Qt.LeftButton:
                delta = QPoint(event.globalPos() - self.oldPos)
                #print(delta)
                self.move(self.x() + delta.x(), self.y() + delta.y())
                self.oldPos = event.globalPos()


        # RESIZE FUNCTIONS----------------------------------------------------------
        # Top resize
        self.MIN_HEIGHT = 80
        def resizeWindowTop(event):
            if event.buttons() == Qt.LeftButton:
                self.globalY = self.pos().y()
                newYPos = event.globalPos().y() - self.globalY
                oldHeight = self.height()
                newHeight = self.MIN_HEIGHT if self.height() - newYPos < self.MIN_HEIGHT else self.height() - newYPos
                self.resize(self.width(), newHeight)
                if oldHeight - self.height() != 0:
                    self.move(self.x(), self.y() + newYPos)

        # Left resize
        def resizeWindowLeft(event):
            if event.buttons() == Qt.LeftButton:
                self.globalX = self.pos().x()
                newXPos = event.globalPos().x() - self.globalX
                oldWidth = self.width()
                self.resize(self.width() - newXPos, self.height())
                if oldWidth - self.width() != 0:
                    self.move(self.x() + newXPos, self.y())

        # Bottom resize
        def resizeWindowBottom(event):
            if event.buttons() == Qt.LeftButton:
                self.globalY = self.pos().y()
                newHeight = self.MIN_HEIGHT if event.globalPos().y() - self.globalY < self.MIN_HEIGHT else event.globalPos().y() - self.globalY
                self.resize(self.width(), newHeight)

        # Right resize
        def resizeWindowRight(event):
            if event.buttons() == Qt.LeftButton:
                self.globalX = self.pos().x()
                newWidth = event.globalPos().x() - self.globalX
                self.resize(newWidth, self.height())

        # TopLeft resize
        def resizeWindowTopLeft(event):
            resizeWindowTop(event)
            resizeWindowLeft(event)

        # TopRight resize
        def resizeWindowTopRight(event):
            resizeWindowTop(event)
            resizeWindowRight(event)

        # BottomLeft resize
        def resizeWindowBottomLeft(event):
            resizeWindowBottom(event)
            resizeWindowLeft(event)

        # BottomRight resize
        def resizeWindowBottomRight(event):
            resizeWindowBottom(event)
            resizeWindowRight(event)

        def doubleClickMaximize(event):
            self.maximize()

        # Making application draggable
        self.oldPos = self.pos()
        self.ui.topBarMiddle.mouseMoveEvent = moveWindow
        self.ui.topBarMiddle.mouseDoubleClickEvent = doubleClickMaximize

        # Making application resizeable
        self.ui.rightGripBorder.mouseMoveEvent = resizeWindowRight
        self.ui.bottomGripBorder.mouseMoveEvent = resizeWindowBottom
        self.ui.leftGripBorder.mouseMoveEvent = resizeWindowLeft
        self.ui.topGripBorder.mouseMoveEvent = resizeWindowTop

        self.ui.topLeftCorner.mouseMoveEvent = resizeWindowTopLeft
        self.ui.topRightCorner.mouseMoveEvent = resizeWindowTopRight
        self.ui.bottomLeftCorner.mouseMoveEvent = resizeWindowBottomLeft
        self.ui.bottomRightCorner.mouseMoveEvent = resizeWindowBottomRight


    # Getting the current position if any mousePressEvent happened
    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def maximize(self):
        self.maximizeToggle ^= True
        if self.maximizeToggle:
            self.showMaximized()
        else:
            self.showNormal()





#-------------------------------------------------------------------------------
if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
