# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 759)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color:rgb(255,255,255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.BorderFrame = QtWidgets.QFrame(self.centralwidget)
        self.BorderFrame.setMinimumSize(QtCore.QSize(0, 1))
        self.BorderFrame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BorderFrame.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.BorderFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BorderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BorderFrame.setObjectName("BorderFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.BorderFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.rightGripBorder = QtWidgets.QFrame(self.BorderFrame)
        self.rightGripBorder.setMinimumSize(QtCore.QSize(1, 0))
        self.rightGripBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightGripBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightGripBorder.setObjectName("rightGripBorder")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rightGripBorder)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rightGripLabel = QtWidgets.QLabel(self.rightGripBorder)
        self.rightGripLabel.setMinimumSize(QtCore.QSize(3, 0))
        self.rightGripLabel.setMaximumSize(QtCore.QSize(3, 16777215))
        self.rightGripLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.rightGripLabel.setText("")
        self.rightGripLabel.setObjectName("rightGripLabel")
        self.horizontalLayout_7.addWidget(self.rightGripLabel)
        self.gridLayout.addWidget(self.rightGripBorder, 1, 2, 1, 1)
        self.bottomGripBorder = QtWidgets.QFrame(self.BorderFrame)
        self.bottomGripBorder.setMinimumSize(QtCore.QSize(0, 0))
        self.bottomGripBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomGripBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomGripBorder.setObjectName("bottomGripBorder")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.bottomGripBorder)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bottomGripLabel = QtWidgets.QLabel(self.bottomGripBorder)
        self.bottomGripLabel.setMinimumSize(QtCore.QSize(0, 3))
        self.bottomGripLabel.setMaximumSize(QtCore.QSize(16777215, 3))
        self.bottomGripLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.bottomGripLabel.setText("")
        self.bottomGripLabel.setObjectName("bottomGripLabel")
        self.horizontalLayout_6.addWidget(self.bottomGripLabel)
        self.gridLayout.addWidget(self.bottomGripBorder, 2, 1, 1, 1)
        self.leftGripBorder = QtWidgets.QFrame(self.BorderFrame)
        self.leftGripBorder.setMinimumSize(QtCore.QSize(1, 0))
        self.leftGripBorder.setStyleSheet("")
        self.leftGripBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftGripBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftGripBorder.setObjectName("leftGripBorder")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.leftGripBorder)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.leftGripLabel = QtWidgets.QLabel(self.leftGripBorder)
        self.leftGripLabel.setMinimumSize(QtCore.QSize(3, 0))
        self.leftGripLabel.setMaximumSize(QtCore.QSize(3, 16777215))
        self.leftGripLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.leftGripLabel.setText("")
        self.leftGripLabel.setObjectName("leftGripLabel")
        self.horizontalLayout_5.addWidget(self.leftGripLabel)
        self.gridLayout.addWidget(self.leftGripBorder, 1, 0, 1, 1)
        self.topGripBorder = QtWidgets.QFrame(self.BorderFrame)
        self.topGripBorder.setMinimumSize(QtCore.QSize(0, 1))
        self.topGripBorder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topGripBorder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topGripBorder.setObjectName("topGripBorder")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.topGripBorder)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.topGripLabel = QtWidgets.QLabel(self.topGripBorder)
        self.topGripLabel.setMinimumSize(QtCore.QSize(0, 3))
        self.topGripLabel.setMaximumSize(QtCore.QSize(16777215, 3))
        self.topGripLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.topGripLabel.setText("")
        self.topGripLabel.setObjectName("topGripLabel")
        self.horizontalLayout_11.addWidget(self.topGripLabel)
        self.gridLayout.addWidget(self.topGripBorder, 0, 1, 1, 1)
        self.appFrame = QtWidgets.QFrame(self.BorderFrame)
        self.appFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.appFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appFrame.setObjectName("appFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.appFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topBar = QtWidgets.QFrame(self.appFrame)
        self.topBar.setMinimumSize(QtCore.QSize(0, 30))
        self.topBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.topBar.setStyleSheet("background: rgb(33,33,33);")
        self.topBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBar.setObjectName("topBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.topBarLeft = QtWidgets.QFrame(self.topBar)
        self.topBarLeft.setMinimumSize(QtCore.QSize(60, 0))
        self.topBarLeft.setMaximumSize(QtCore.QSize(60, 16777215))
        self.topBarLeft.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.topBarLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBarLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBarLeft.setObjectName("topBarLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.topBarLeft)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.topBarLeft)
        self.label.setStyleSheet("color:rgb(255,255,255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ressources/icons/resize.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.topBarLeft)
        self.topBarMiddle = QtWidgets.QFrame(self.topBar)
        self.topBarMiddle.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(33, 33,33, 255), stop:1 rgba(40, 40, 40, 255))")
        self.topBarMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topBarMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topBarMiddle.setObjectName("topBarMiddle")
        self.horizontalLayout_3.addWidget(self.topBarMiddle)
        self.minMaxExitFrame = QtWidgets.QFrame(self.topBar)
        self.minMaxExitFrame.setMinimumSize(QtCore.QSize(105, 0))
        self.minMaxExitFrame.setMaximumSize(QtCore.QSize(150, 16777215))
        self.minMaxExitFrame.setStyleSheet("")
        self.minMaxExitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.minMaxExitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.minMaxExitFrame.setObjectName("minMaxExitFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.minMaxExitFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimizeBtn = QtWidgets.QPushButton(self.minMaxExitFrame)
        self.minimizeBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.minimizeBtn.setMouseTracking(False)
        self.minimizeBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(33,33,33);\n"
"background-image: url(:/icons/minimize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgb(50,50,50);\n"
"background-image:url(:/icons/minimize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgb(80,80,80);\n"
"background-image:url(:/icons/minimize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"")
        self.minimizeBtn.setText("")
        self.minimizeBtn.setFlat(True)
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_2.addWidget(self.minimizeBtn)
        self.maximizeBtn = QtWidgets.QPushButton(self.minMaxExitFrame)
        self.maximizeBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.maximizeBtn.setMouseTracking(False)
        self.maximizeBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(33,33,33);\n"
"background-image:url(:/icons/maximize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgb(50,50,50);\n"
"background-image:url(:/icons/maximize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgb(80,80,80);\n"
"background-image:url(:/icons/maximize3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}")
        self.maximizeBtn.setText("")
        self.maximizeBtn.setFlat(True)
        self.maximizeBtn.setObjectName("maximizeBtn")
        self.horizontalLayout_2.addWidget(self.maximizeBtn)
        self.exitBtn = QtWidgets.QPushButton(self.minMaxExitFrame)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.exitBtn.setMaximumSize(QtCore.QSize(50, 30))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(33,33,33);\n"
"background-image:url(:/icons/close3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"background: rgb(50,50,50);\n"
"background-image:url(:/icons/close3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"QPushButton:pressed{\n"
"background: rgb(80,80,80);\n"
"background-image:url(:/icons/close3.png);\n"
"background-position: center;\n"
"background-repeat:none;\n"
"border:0px;\n"
"}\n"
"")
        self.exitBtn.setText("")
        self.exitBtn.setFlat(True)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.horizontalLayout_3.addWidget(self.minMaxExitFrame)
        self.verticalLayout_5.addWidget(self.topBar)
        self.mainPage = QtWidgets.QFrame(self.appFrame)
        self.mainPage.setStyleSheet("background-color:rgb(40,40,40);")
        self.mainPage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainPage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainPage.setObjectName("mainPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBar = QtWidgets.QFrame(self.mainPage)
        self.leftBar.setMinimumSize(QtCore.QSize(60, 0))
        self.leftBar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftBar.setStyleSheet("background-color: rgb(33,33,33)")
        self.leftBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBar.setObjectName("leftBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftBar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.leftBar)
        self.contentFrame = QtWidgets.QFrame(self.mainPage)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.contentFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pages = QtWidgets.QStackedWidget(self.contentFrame)
        self.pages.setObjectName("pages")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.pages.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.pages.addWidget(self.page2)
        self.horizontalLayout_4.addWidget(self.pages)
        self.horizontalLayout.addWidget(self.contentFrame)
        self.verticalLayout_5.addWidget(self.mainPage)
        self.gridLayout.addWidget(self.appFrame, 1, 1, 1, 1)
        self.bottomLeftCorner = QtWidgets.QFrame(self.BorderFrame)
        self.bottomLeftCorner.setMinimumSize(QtCore.QSize(3, 3))
        self.bottomLeftCorner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bottomLeftCorner.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.bottomLeftCorner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomLeftCorner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomLeftCorner.setObjectName("bottomLeftCorner")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.bottomLeftCorner)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bottomLeftLabel = QtWidgets.QLabel(self.bottomLeftCorner)
        self.bottomLeftLabel.setMinimumSize(QtCore.QSize(1, 1))
        self.bottomLeftLabel.setMaximumSize(QtCore.QSize(4, 4))
        self.bottomLeftLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.bottomLeftLabel.setMouseTracking(False)
        self.bottomLeftLabel.setStyleSheet("")
        self.bottomLeftLabel.setText("")
        self.bottomLeftLabel.setObjectName("bottomLeftLabel")
        self.horizontalLayout_8.addWidget(self.bottomLeftLabel)
        self.gridLayout.addWidget(self.bottomLeftCorner, 2, 0, 1, 1)
        self.topLeftCorner = QtWidgets.QFrame(self.BorderFrame)
        self.topLeftCorner.setMinimumSize(QtCore.QSize(3, 3))
        self.topLeftCorner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.topLeftCorner.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.topLeftCorner.setStyleSheet("")
        self.topLeftCorner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topLeftCorner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLeftCorner.setObjectName("topLeftCorner")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.topLeftCorner)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.topLeftLabel = QtWidgets.QLabel(self.topLeftCorner)
        self.topLeftLabel.setMinimumSize(QtCore.QSize(1, 1))
        self.topLeftLabel.setMaximumSize(QtCore.QSize(4, 4))
        self.topLeftLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.topLeftLabel.setText("")
        self.topLeftLabel.setObjectName("topLeftLabel")
        self.horizontalLayout_9.addWidget(self.topLeftLabel)
        self.gridLayout.addWidget(self.topLeftCorner, 0, 0, 1, 1)
        self.topRightCorner = QtWidgets.QFrame(self.BorderFrame)
        self.topRightCorner.setMinimumSize(QtCore.QSize(3, 3))
        self.topRightCorner.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.topRightCorner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topRightCorner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRightCorner.setObjectName("topRightCorner")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.topRightCorner)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.topRightLabel = QtWidgets.QLabel(self.topRightCorner)
        self.topRightLabel.setMinimumSize(QtCore.QSize(1, 1))
        self.topRightLabel.setMaximumSize(QtCore.QSize(4, 4))
        self.topRightLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.topRightLabel.setText("")
        self.topRightLabel.setObjectName("topRightLabel")
        self.horizontalLayout_12.addWidget(self.topRightLabel)
        self.gridLayout.addWidget(self.topRightCorner, 0, 2, 1, 1)
        self.bottomRightCorner = QtWidgets.QFrame(self.BorderFrame)
        self.bottomRightCorner.setMinimumSize(QtCore.QSize(3, 3))
        self.bottomRightCorner.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.bottomRightCorner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomRightCorner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRightCorner.setObjectName("bottomRightCorner")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.bottomRightCorner)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bottomRightLabel = QtWidgets.QLabel(self.bottomRightCorner)
        self.bottomRightLabel.setMinimumSize(QtCore.QSize(1, 1))
        self.bottomRightLabel.setMaximumSize(QtCore.QSize(4, 4))
        self.bottomRightLabel.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.bottomRightLabel.setText("")
        self.bottomRightLabel.setObjectName("bottomRightLabel")
        self.horizontalLayout_10.addWidget(self.bottomRightLabel)
        self.gridLayout.addWidget(self.bottomRightCorner, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.BorderFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import icons_rc
